Update admin_footer-post.php and load-edit.php hooks for handling HPOS screens
godaddy-wordpress/wc-plugin-framework pull request #587
Opened 2023-01-30 21:37 UTC by sharazghouri

## Summary

While testing Authorize mode transaction, I noticed that the Capture Charge button is not showing on the order edit screen.  I figured out why it's not showing,   [admin_footer-edit.php](https://github.com/godaddy-wordpress/wc-plugin-framework/blob/master/woocommerce/payment-gateway/admin/class-sv-wc-payment-gateway-admin-order.php#L65) hook not working in HPOS-supported WooCommecre.  First, it's not a normal post-type edit screen that's why this hook not working. 

### Story: [MWC-10260](https://godaddy-corp.atlassian.net/browse/MWC-10260) ,  [MWC-10305](https://godaddy-corp.atlassian.net/browse/MWC-10305)

2023-01-30 21:58 UTC, sharazghouri commented on woocommerce/payment-gateway/admin/class-sv-wc-payment-gateway-admin-order.php
`$post_type` and `$post_status` will not work in WooCommerce to check post type and post status. We need more helper methods for these operations.  I'm working on it.

2023-02-02 10:25 UTC, unfulvio-godaddy requested changes

2023-02-02 10:25 UTC, unfulvio-godaddy commented on woocommerce/compatibility/class-sv-wc-order-compatibility.php
> +	}
I don't think this method would be needed. As it is currently it also returns void / does not handle scenarios where global is neither order or post. But besides, I don't think we want methods that return different objects that aren't related.

2023-02-02 10:25 UTC, unfulvio-godaddy commented on woocommerce/compatibility/class-sv-wc-order-compatibility.php
> +
I am also not sure if this method is needed either.

Also this method does not account for the possibility neither global is set and will return void.

But also, I believe if the purpose of adding this is solely to fix the logic in the hook callback below, then we could just move the corresponding logic in the callback. I made a quick search on plugins and I don't think there are more instances of `admin_footer-edit.php`. Sure enough, there could be more contexts where we need detection of an order edit screen - but in that case we could benefit from a different helper method.

2023-02-03 10:28 UTC, unfulvio-godaddy reviewed
I checked the results of get_current_screen and other data available in the orders screen or the order edit screen... it's not ideal but maybe we can just use both the screen id and elements from the `$_GET` request until we find a better/robust way to handle this.

Something along the lines of:

```php


	/**
	 * Determines if the current admin screen is for the orders.
	 * 
	 * @return bool
	 */
	public static function is_orders_screen() : bool {

		$current_screen = SV_WC_Helper::get_current_screen();

		if ( ! $current_screen ) {
			return false;
		}

		if ( ! SV_WC_Plugin_Compatibility::is_hpos_enabled() ) {
			return 'edit-shop_order' === $current_screen->id;
		}

		return static::get_order_screen_id() === $current_screen->id
			&& isset( $_GET['page'] )
			&& $_GET['page'] === 'wc-orders';
	}

	
	/**
	 * Determines if the current admin screen is for adding or editing an order. 
	 * 
	 * @since x.y.z
	 * 
	 * @return bool
	 */
	public static function is_order_edit_screen() : bool {

		$current_screen = SV_WC_Helper::get_current_screen();

		if ( ! $current_screen ) {
			return false;
		}

		if ( ! SV_WC_Plugin_Compatibility::is_hpos_enabled() ) {
			return 'edit-shop_order' === $current_screen->id;
		}

		return static::get_order_screen_id() === $current_screen->id
			&& isset( $_GET['page'], $_GET['action'] )
			&& $_GET['page'] === 'wc-orders'
			&& in_array( $_GET['action'], [ 'new', 'edit'], true );
	}


```

2023-02-06 03:49 UTC, unfulvio-godaddy approved these changes

2023-02-06 03:49 UTC, merged