Use gateway FW path when loading block handler files
godaddy-wordpress/wc-plugin-framework pull request #676
Opened 2024-05-01 03:34 UTC by itambek-godaddy

# Summary

Some FW files only exist in gateway plugins due to our build process. This change ensures that gateway plugins will load block handler files from the gateway FW path, rather than a generic FW path.

This fix is similar to https://github.com/gdcorp-partners/woocommerce-gateway-intuit-qbms/pull/11/files

### Story: [MWC-16371](https://godaddy-corp.atlassian.net/browse/MWC-16371)

2024-05-01 21:30 UTC, nikolas4175-godaddy requested changes

2024-05-01 21:30 UTC, nikolas4175-godaddy commented on woocommerce/payment-gateway/class-sv-wc-payment-gateway-plugin.php
> +		require_once( $this->get_payment_gateway_framework_path() . '/Blocks/Blocks_Handler.php' );
```suggestion
		require_once( $this->get_framework_path() . '/Blocks/Blocks_Handler.php' );
```
AFAICT the base `Blocks_Handler` file doesn't exist under `/payment-gateway/` so this one should still load from the FW root dir.

2024-05-01 21:30 UTC, nikolas4175-godaddy commented on woocommerce/payment-gateway/Blocks/Gateway_Blocks_Handler.php
> +			require_once( $plugin->get_payment_gateway_framework_path() . '/payment-gateway/Blocks/Gateway_Checkout_Block_Integration.php' );
```suggestion
			require_once( $plugin->get_payment_gateway_framework_path() . '/Blocks/Gateway_Checkout_Block_Integration.php' );
```
`/payment-gateway` is included in the `get_payment_gateway_framework_path()` return value

2024-05-01 21:30 UTC, nikolas4175-godaddy commented on woocommerce/payment-gateway/class-sv-wc-payment-gateway-plugin.php
> +		require_once( $this->get_payment_gateway_framework_path() . '/payment-gateway/Blocks/Gateway_Blocks_Handler.php' );
```suggestion
		require_once( $this->get_payment_gateway_framework_path() . '/Blocks/Gateway_Blocks_Handler.php' );
```
Same as above, no need to repeat `/payment-gateway`

2024-05-02 11:41 UTC, itambek-godaddy commented
@nikolas4175-godaddy thanks for the review and the catch in the path. I did test this with auth.net to see if I would get any fatal errors, but I think I had some other gateway plugin active as well, so the code _seemed_ to work. My apologies, shouod have been more thorough.

2024-05-04 00:29 UTC, nikolas4175-godaddy approved these changes
Updates LGTM!

2024-05-06 05:46 UTC, merged